### ISSUE TITLE
Error running examples

### ISSUE THREAD

**Issue by JairoRotava** [lessthanoptimal/KBoofExamples#1]
I cloned the KBoofExamples, and tried to build/run it on Intellij Idea 2013. When I try to run any example, there is an error similar to this one:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.ddogleg.struct.FastQueue.<init>(java.lang.Class, boolean)'
	at boofcv.alg.shapes.edge.SnapToLineEdge.<init>(SnapToLineEdge.java:70)
	at boofcv.alg.shapes.polygon.RefinePolygonToGrayLine.<init>(RefinePolygonToGrayLine.java:101)
	at boofcv.factory.shape.FactoryShapeDetector.refinePolygon(FactoryShapeDetector.java:126)
	at boofcv.factory.shape.FactoryShapeDetector.polygon(FactoryShapeDetector.java:98)
	at boofcv.factory.fiducial.FactoryFiducial.qrcode(FactoryFiducial.java:199)
	at QrCodeWebcamKt.main(QrCodeWebcam.kt:14)
	at QrCodeWebcamKt.main(QrCodeWebcam.kt)

I think it is something with FastQueue, but I don't know how to fix it.

**Comment by lessthanoptimal** [comment]
You probably have an out of date SNAPSHOT jar for DDogleg. Kotlin support is still new and isn't included in a stable release yet. That will be fixed "soon"

1) Clean then rebuild the project.
2) If that doesn't work, nuke your local maven repo. Search online how to do that.

**Comment by JairoRotava** [comment]
Thanks, it is working. Had to refresh the dependencies: right click the gradle project - Refresh gradle dependencies
